name: Build and Deploy Container
on:
  workflow_run:
    workflows: ["Run Tests & Lint"]  
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' 
      && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}








            